[package]
name = "news-migrations"
version = "0.1.0"
authors = ["imac"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
barrel = { version = "0.6.5", features =["pg"] }
postgres = "0.17.2" 